//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5120___VicEnerG.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Calculator
    {
        public int Id { get; set; }
        public double area { get; set; } = 1.6;
        public double efficiency { get; set; } = 0.156;
        public double performanceRatio { get; set; } = 0.75;
        
        // Some variables of the formula are pre-define with value
        // This method will calculate and return the monthly solar output of a given station
        public IList<double> CalculateSolarOutput(IList<double> StationData, int NumberPanels)    
        {
            IList<double> TotalOutput = new List<double>();
            foreach (double Radiation in StationData)
            {
                // Formular: E = A * r * H * PR * Number of panels
                double EachOutput = area * efficiency * performanceRatio * Radiation * NumberPanels;
                // Round each output to 2 decimals only
                double RoundedOutput = Math.Round(EachOutput);
                TotalOutput.Add(RoundedOutput);
            }
            return TotalOutput;
        }

        // This method will calculate the amount of CO2 correspond to the elecrticity output
        public double CalculateCO2(double AnnualOutput)
        {
            // The formular
            double CO2 = Math.Round(AnnualOutput * 0.00113,2);
            return CO2;
        }

        // This method will calculate the extra hours that can use by a list of appliances
        // The method will return a dictionary contained all appliances information along with their extra hours.
        public IDictionary<String, List<int>> CalculateUsage(IList<Appliance> ApplianceList, IList<double> MonthlyOutput)
        {
            // Initial the dictionary 
            IDictionary<String, List<int>> Usage = new Dictionary<String, List<int>>();
            foreach (Appliance App in ApplianceList) 
            {
                double EachUsage = App.usage;
                List<int> Extrahours = new List<int>();
                foreach (double MonthlyData in MonthlyOutput)
                {
                    // Total divide each usage will result the extra hours 
                    int Result = (int)Math.Round(MonthlyData / EachUsage);
                    // Add the extra hours data into the list
                    Extrahours.Add(Result);
                }
                // Add the appliance object and the corresponding extra hours list into the dictionary
                Usage.Add(App.applianceName, Extrahours);
            }
            return Usage;
        }
    }
}
